### ISSUE TITLE
Only data or links expected in relationships 

### ISSUE THREAD

**Issue by asharmaupland** [singer-io/tap-outreach#16]
Getting this error while extracting data from outreach to sql  using Stitch data. Any Solution for this issue ?

INFO HTTP request to "accounts" endpoint took 2.105s, returned status code 200
2022-02-08 15:18:19,794Z target - INFO Requests complete, stopping loop
2022-02-08 15:18:20,324Z    tap - INFO [smart-services] event successfully sent to kafka: com.stitchdata.streamRecordCount [6] at offset None
2022-02-08 15:18:20,324Z    tap - INFO replicated 0 records from "accounts" endpoint
2022-02-08 15:18:20,325Z    tap - CRITICAL Only `data` or `links` expected in relationships
2022-02-08 15:18:20,325Z    tap - Traceback (most recent call last):
2022-02-08 15:18:20,325Z    tap -   File "tap-env/bin/tap-outreach", line 33, in <module>
2022-02-08 15:18:20,325Z    tap -     sys.exit(load_entry_point('tap-outreach==0.7.0', 'console_scripts', 'tap-outreach')())
2022-02-08 15:18:20,325Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/singer/utils.py", line 229, in wrapped
2022-02-08 15:18:20,325Z    tap -     return fnc(*args, **kwargs)
2022-02-08 15:18:20,325Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_outreach/__init__.py", line 46, in main
2022-02-08 15:18:20,325Z    tap -     sync(client,
2022-02-08 15:18:20,325Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_outreach/sync.py", line 336, in sync
2022-02-08 15:18:20,325Z    tap -     sync_endpoint(client, config, catalog, state,
2022-02-08 15:18:20,325Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_outreach/sync.py", line 313, in sync_endpoint
2022-02-08 15:18:20,325Z    tap -     max_modified = process_records(stream,
2022-02-08 15:18:20,325Z    tap -   File "/code/orchestrator/tap-env/lib/python3.8/site-packages/tap_outreach/sync.py", line 219, in process_records
2022-02-08 15:18:20,325Z    tap -     raise Exception(
2022-02-08 15:18:20,325Z    tap - Exception: Only `data` or `links` expected in relationships
2022-02-08 15:18:20,326Z   main - INFO Target exited normally with status 0
2022-02-08 15:18:21,324Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [15] at offset None
2022-02-08 15:18:21,330Z   main - INFO No tunnel subprocess to tear down
2022-02-08 15:18:21,330Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "Only `data` or `links` expected in relationships". Target succeeded.

**Comment by samlevan** [comment]
Ditto on this one. Reporting the same issue. Outreach tap has started failing. It fails when trying to pull the "accounts" and the "prospects" entities (it continues to work for other tables). Something probably changed in the Outreach API. Would love some help from the community.

**Comment by danielalvesvm** [comment]
Apparently the "prospects" has been fixed already (today) but the "accounts"s still returning the same error.

**Comment by willhasgithub** [comment]
Confirmed: syncing "prospects" no longer throws an error.

**Comment by asharmaupland** [comment]
Yes prospects issue resolved.

**Comment by willhasgithub** [comment]
Syncing "accounts" no longer throws an error.

**Comment by danielalvesvm** [comment]
all back to normal here, thanks!

**Comment by asharmaupland** [comment]
Problem Solved.

Thanks
________________________________
