### ISSUE TITLE
`updaterId` exists as both an attribute and generated relationship name

### ISSUE THREAD

**Issue by asharmaupland** [singer-io/tap-outreach#20]
2022-12-15 17:46:46,795Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/__init__.py", line 46, in main
2022-12-15 17:46:46,795Z    tap -     sync(client,
2022-12-15 17:46:46,795Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/sync.py", line 336, in sync
2022-12-15 17:46:46,795Z    tap -     sync_endpoint(client, config, catalog, state,
2022-12-15 17:46:46,795Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/sync.py", line 313, in sync_endpoint
2022-12-15 17:46:46,795Z    tap -     max_modified = process_records(stream,
2022-12-15 17:46:46,795Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/sync.py", line 231, in process_records
2022-12-15 17:46:46,795Z    tap -     raise Exception(
2022-12-15 17:46:46,795Z    tap - Exception: `updaterId` exists as both an attribute and generated relationship name
2022-12-15 17:46:46,829Z target - INFO Requests complete, stopping loop
2022-12-15 17:46:46,868Z   main - INFO Target exited normally with status 0
2022-12-15 17:46:47,564Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [4] at offset None
2022-12-15 17:46:47,566Z   main - INFO No tunnel subprocess to tear down
2022-12-15 17:46:47,566Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "`updaterId` exists as both an attribute and generated relationship name". Target succeeded.

**Comment by asharmaupland** [comment]
We encountered an error while replicating data from Outreach
The message is : `updaterId` exists as both an attribute and generated relationship name
Please help to solve the problem

**Comment by 5amCurfew** [comment]
We are also running into this. Given that previously Outreach made updates to similar issues quickly (ref. github.com/singer-io/tap-outreach/issues/16#issuecomment-1034007811) we are going to wait over the weekend expecting a fix (the tap probably assumes that `attributes` and `relationships` are mutually exclusive).

If we don't see a change soon we are most likely going to just remove the `if fk_field_name in record_flat:` block here github.com/singer-io/tap-outreach/blob/d3ad0ee815c0d4261385576ff235f93efb1ad176/tap_outreach/sync.py#L230 as we don't mind `relationships` taking precedence over `attributes` (removing `if fk_field_name in record_flat:` block will lead to it being over written by `relationships`).

**Comment by scottoneto** [comment]
Following this thread as I am experiencing the same "updaterId exists as both an attribute and generated relationship name" issue replicating data from our Outreach.io account.

**Comment by fidel-perez** [comment]
We have encountered this issue too. 
I am assuming more messages like this one do not contribute any further to the conversation so let's just react with an emoji to this message or @scottoneto message if you came here for the same reason.

**Comment by asharmaupland** [comment]
Any Update on this @5amCurfew

**Comment by asharmaupland** [comment]
>  Hi @5amCurfew

 Have you implemented this ''remove the if fk_field_name in record_flat''??

**Comment by 5amCurfew** [comment]
We have just commented out the block as mentioned above. We aren't removing anything we are just letting the `relationship` value of it take precedence over the `attribute` value. No issues by the looks of it with respect to the catalog etc

**Comment by asharmaupland** [comment]
@5amCurfew  It is fixed or you are going to fix it. I am still getting the same error .

New Log:


2023-01-04 10:45:56,388Z    tap - INFO replicated 0 records from "prospects" endpoint
2023-01-04 10:45:56,389Z    tap - CRITICAL `updaterId` exists as both an attribute and generated relationship name
2023-01-04 10:45:56,389Z    tap - Traceback (most recent call last):
2023-01-04 10:45:56,389Z    tap -   File "/code/orchestrator/tap-env/bin/tap-outreach", line 33, in <module>
2023-01-04 10:45:56,389Z    tap -     sys.exit(load_entry_point('tap-outreach==0.7.0', 'console_scripts', 'tap-outreach')())
2023-01-04 10:45:56,389Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/utils.py", line 229, in wrapped
2023-01-04 10:45:56,389Z    tap -     return fnc(*args, **kwargs)
2023-01-04 10:45:56,389Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/__init__.py", line 46, in main
2023-01-04 10:45:56,389Z    tap -     sync(client,
2023-01-04 10:45:56,390Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/sync.py", line 336, in sync
2023-01-04 10:45:56,390Z    tap -     sync_endpoint(client, config, catalog, state,
2023-01-04 10:45:56,390Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/sync.py", line 313, in sync_endpoint
2023-01-04 10:45:56,390Z    tap -     max_modified = process_records(stream,
2023-01-04 10:45:56,390Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/sync.py", line 231, in process_records
2023-01-04 10:45:56,390Z    tap -     raise Exception(
2023-01-04 10:45:56,390Z    tap - Exception: `updaterId` exists as both an attribute and generated relationship name
2023-01-04 10:45:56,421Z target - INFO Requests complete, stopping loop
2023-01-04 10:45:56,461Z   main - INFO Target exited normally with status 0
2023-01-04 10:45:56,464Z   main - INFO No tunnel subprocess to tear down
2023-01-04 10:45:56,464Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "`updaterId` exists as both an attribute and generated relationship name". Target succeeded.

**Comment by 5amCurfew** [comment]
We have forked the singer tap expecting it to be fixed/resolved by updates to the Outreach API at some point given previous updates (refer to github.com/https://github.com/singer-io/tap-outreach/issues/16#issuecomment-1034007811)

**Comment by seanlally** [comment]
Joining in late here, but does this mean this issue won't be fixed until it is fixed on Outreach's end? We are experiencing the same error.

**Comment by seanlally** [comment]
@5amCurfew 

From outreach support directly:

```Hi Slally,
 
Thanks for additional details and context! 
 
I heard back from the team and it looks like we recently pushed this field to production, however it is not a stable feature yet. 
 
I also did some testing myself, and I can fetch prospects with that field via API. 
We don't partner with Stitch at the moment so we don't have any visibility on this integration. But it looks like they might enforce a set of fields from their end and that would be the reason of this error. 
I would recommend reaching out to them directly since they own the integration and they should have more insight of what is going on. 
 
From the Outreach side, I can confirm, that is a new field, it is still in the development but it shouldn't fail when retrieving data via API. 
 
I wish I could help more. Please let me know if you or Stitch team have any questions, more than happy to schedule some time to troubleshoot together if I can help in any way. ```

**Comment by scottoneto** [comment]
@seanlally This is an integration that is run within Stitch, but Stitch does not actively support it by their team. Maintenance (and support) of this integration are performed by the Singer community, including bug fixing/adapting to new versions of the this API. Our team is still experiencing the issue as well, but hoping it gets rectified or we will end up putting in our own pull request.

**Comment by seanlally** [comment]
Yes, the point of the outreach support post was to show that Outreach won't be fixing this on their end, because to them it is working as expected. 5am's last message made it sound like they were just going to wait for Outreach to fix it, which isn't going to happen.

**Comment by asharmaupland** [comment]
@seanlally  @5amCurfew  Is there an ETA on this fix?

**Comment by asharmaupland** [comment]
@seanlally @5amCurfew  Any update on this issue?

**Comment by asharmaupland** [comment]
Any update on this? 
@seanlally @5amCurfew

**Comment by joe-rayment** [comment]
We are also experiencing this issue. We went through a back and forth with Stitch Support and they suggested we raise it here

**Comment by seanlally** [comment]
There are two outstanding PRs that attempt to fix this issue. We're just waiting for either one of them to be reviewed and accepted.

**Comment by asharmaupland** [comment]
@seanlally  Is there an ETA on this fix? This is very critical for our business.

**Comment by seanlally** [comment]
No idea, just waiting for singer.io folks to do something.

**Comment by charlie-mclaughlin** [comment]
I've been following along for the last few months as well, is there any evidence that singer.io is still a functioning group? Seems like the lights are on (the website works) but no one is home. I appreciate @seanlally trying a PR, but we might be better off just creating our own API requests to Outreach.

**Comment by asharmaupland** [comment]
@seanlally Any update on this?

**Comment by seanlally** [comment]
Still haven't heard anything from singer-io. We use this tap through Stitch and they said they can't do anything from their end. They suggested we slack or tweet singer-io, but the singer-io twitter account has been idle for 3 years and the slack link on the singer-io webpage is broken (for me at least).

**Comment by g-chris** [comment]
@seanlally Thank you for all the work you've put in on this, along with everyone else for raising this issue

**Comment by ismael-contentful** [comment]
Any luck @g-chris ? We are having the same issue for months now too.

Thanks for raising it in the Slack channel.

**Comment by charlie-mclaughlin** [comment]
In case anyone else is trying to bring this data to Snowflake, I'm having more luck with getting Outreach data directly from Snowflake Marketplace.

**Comment by g-chris** [comment]
> Any luck @g-chris ? We are having the same issue for months now too.

**Comment by asharmaupland** [comment]
@5amCurfew  @seanlally  Do you have any idea about this issue?
[](https://github.com/singer-io/tap-outreach/issues/24)

**Comment by asharmaupland** [comment]
@seanlally @sgandhi1311  Any update on this?

**Comment by sgandhi1311** [comment]
@asharmaupland 
The fix provided by @seanlally  #25 is deployed to prod. Please validate whether you are getting the expected results.

**Comment by g-chris** [comment]
> @asharmaupland The fix provided by @seanlally #25 is deployed to prod. Please validate whether you are getting the expected results.

I'm now seeing up to date data on the prospect table so looks like the fix worked.

Thank you @sgandhi1311 and @seanlally!

**Comment by ismael-contentful** [comment]
It also works now for us. Thanks @sgandhi1311 and @seanlally !

**Comment by seanlally** [comment]
Yay, it's working. Thanks everyone!
