### ISSUE TITLE
Encountered an error while attempting to replicate data from Outreach(Error testing Outreach authentication)

### ISSUE THREAD

**Issue by asharmaupland** [singer-io/tap-outreach#24]
I am getting error while attempting to replicate data from Outreach(Error testing Outreach authentication) using stitch API.
Has anyone seen this?

2023-04-24 06:54:42,079Z    tap -     response.raise_for_status()
2023-04-24 06:54:42,079Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/requests/models.py", line 941, in raise_for_status
2023-04-24 06:54:42,079Z    tap -     raise HTTPError(http_error_msg, response=self)
2023-04-24 06:54:42,079Z    tap - requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.outreach.io/oauth/token
2023-04-24 06:54:42,079Z    tap - 
2023-04-24 06:54:42,079Z    tap - During handling of the above exception, another exception occurred:
2023-04-24 06:54:42,079Z    tap - 
2023-04-24 06:54:42,080Z    tap - Traceback (most recent call last):
2023-04-24 06:54:42,080Z    tap -   File "/code/orchestrator/tap-env/bin/tap-outreach", line 33, in <module>
2023-04-24 06:54:42,080Z    tap -     sys.exit(load_entry_point('tap-outreach==0.7.0', 'console_scripts', 'tap-outreach')())
2023-04-24 06:54:42,080Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/utils.py", line 229, in wrapped
2023-04-24 06:54:42,080Z    tap -     return fnc(*args, **kwargs)
2023-04-24 06:54:42,080Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/__init__.py", line 45, in main
2023-04-24 06:54:42,080Z    tap -     check_auth(client)
2023-04-24 06:54:42,080Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_outreach/__init__.py", line 33, in check_auth
2023-04-24 06:54:42,080Z    tap -     raise Exception('Error testing Outreach authentication')
2023-04-24 06:54:42,080Z    tap - Exception: Error testing Outreach authentication
2023-04-24 06:54:42,109Z target - INFO Requests complete, stopping loop
2023-04-24 06:54:42,148Z   main - INFO Target exited normally with status 0
2023-04-24 06:54:42,151Z   main - INFO No tunnel subprocess to tear down
2023-04-24 06:54:42,151Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "Error testing Outreach authentication". Target succeeded.

**Comment by dmosorast** [comment]
It seems that something has happened on the Outreach side with the OAuth app used by Stitch and the backend system is rejecting authorization requests. We've reached out to try to get to the bottom of it.

**Comment by guimolnar** [comment]
I have the same issue, couldn't authorize the integration during set up via Stitch's UI

**Comment by dmosorast** [comment]
No updates yet from our communication thread with Outreach, but if folks come upon this issue and are blocked by this error, I'd encourage you to reach out to Outreach support to provide more context and express the ongoing impact.

**Comment by dmosorast** [comment]
Just a quick update, we have been able to create a new OAuth app for this integration, and are in the process of getting it Published for general usage. Will update here when it's ready. This will require re-authorizing the connection in the Stitch UI.

**Comment by dmosorast** [comment]
@asharmaupland @guimolnar The OAuth app has been fixed.

You will need to go into the connection settings for your connection in Stitch and re-authorize with the new app, and you should be good to go!

**Comment by asharmaupland** [comment]
Its working fine. thanks

**Comment by sgandhi1311** [comment]
Issue is resolved. User had to re-authorize the connection.
